In [1]:
import pandas as pd 
import numpy as np

In [2]:
sheet=pd.ExcelFile("./Data/test_data.xlsx")
sheet.sheet_names

['EB',
 'LB',
 'Healthy',
 'EB_Train',
 'LB_Train',
 'Healthy_Train',
 'Txtr_feature_reduce',
 'Opt_feature_values']

In [3]:
df1=sheet.parse('EB')
df1.head()

,Filename,Autocorrelation,Contrast,Correlation,Correlation.1,Cluster Prominence,Cluster Shade,Dissimilarity,Energy,Entropy,...,Sum of sqaures: Variance,Sum average,Sum variance,Sum entropy,Difference variance,Difference entropy,Information measure of correlation1,Informaiton measure of correlation2,Inverse difference normalized,Inverse difference moment normalized
0,image1.jpg,4.937605,0.423813,0.894121,0.894121,231.248614,32.252113,0.232233,0.518499,1.458699,...,5.094305,3.548803,12.964904,1.228323,0.423813,0.586963,-0.528501,0.805223,0.976092,0.994058
1,image2.jpg,2.551722,0.259480,0.871947,0.871947,202.027005,25.453599,0.109989,0.813569,0.644821,...,2.641339,2.583464,7.927913,0.549805,0.259480,0.315387,-0.538252,0.614395,0.989201,0.996550
2,image3.jpg,6.206039,0.618669,0.881609,0.881609,290.479083,38.493259,0.287417,0.465086,1.622099,...,6.453880,3.951214,16.582751,1.352757,0.618669,0.663400,-0.495262,0.809447,0.971216,0.991679
3,image4.jpg,1.885596,0.194235,0.828962,0.828962,82.500028,12.126492,0.090015,0.849845,0.524957,...,1.945784,2.379112,5.820273,0.444227,0.194235,0.272537,-0.521013,0.555576,0.991032,0.997319
4,image5.jpg,4.790395,0.481035,0.890599,0.890599,343.387103,44.837110,0.210380,0.629436,1.159005,...,4.978558,3.366307,14.007415,0.979534,0.481035,0.521808,-0.517051,0.743680,0.979213,0.993550

In [4]:
df1.columns

Index(['Filename', 'Autocorrelation', 'Contrast', 'Correlation',
       'Correlation.1', 'Cluster Prominence', 'Cluster Shade', 'Dissimilarity',
       'Energy', 'Entropy', ' Homogeneity', 'Homogeneity: [2]',
       'Maximum probability:', 'Sum of sqaures: Variance', 'Sum average',
       'Sum variance', 'Sum entropy', 'Difference variance',
       'Difference entropy ', 'Information measure of correlation1 ',
       'Informaiton measure of correlation2', 'Inverse difference normalized',
       'Inverse difference moment normalized'],
      dtype='object')

In [5]:
df2=sheet.parse('LB')
df2.columns

Index(['Filename', 'Autocorrelation', 'Contrast', 'Correlation',
       'Correlation.1', 'Cluster Prominence', 'Cluster Shade', 'Dissimilarity',
       'Energy', 'Entropy', ' Homogeneity', 'Homogeneity: [2]',
       'Maximum probability:', 'Sum of sqaures: Variance', 'Sum average',
       'Sum variance', 'Sum entropy', 'Difference variance',
       'Difference entropy ', 'Information measure of correlation1 ',
       'Informaiton measure of correlation2', 'Inverse difference normalized',
       'Inverse difference moment normalized'],
      dtype='object')

In [6]:
df3=sheet.parse('Healthy')
df3.columns

Index(['Filename', 'Autocorrelation', 'Contrast', 'Correlation',
       'Correlation.1', 'Cluster Prominence', 'Cluster Shade', 'Dissimilarity',
       'Energy', 'Entropy', ' Homogeneity', 'Homogeneity: [2]',
       'Maximum probability:', 'Sum of sqaures: Variance', 'Sum average',
       'Sum variance', 'Sum entropy', 'Difference variance',
       'Difference entropy ', 'Information measure of correlation1 ',
       'Informaiton measure of correlation2', 'Inverse difference normalized',
       'Inverse difference moment normalized'],
      dtype='object')

In [7]:
print(len(df1.columns),len(df2.columns),len(df3.columns))

23 23 23

In [8]:
df1=df1.loc[:,~df1.columns.str.contains('^Unnamed')]
df1.head()

,Filename,Autocorrelation,Contrast,Correlation,Correlation.1,Cluster Prominence,Cluster Shade,Dissimilarity,Energy,Entropy,...,Sum of sqaures: Variance,Sum average,Sum variance,Sum entropy,Difference variance,Difference entropy,Information measure of correlation1,Informaiton measure of correlation2,Inverse difference normalized,Inverse difference moment normalized
0,image1.jpg,4.937605,0.423813,0.894121,0.894121,231.248614,32.252113,0.232233,0.518499,1.458699,...,5.094305,3.548803,12.964904,1.228323,0.423813,0.586963,-0.528501,0.805223,0.976092,0.994058
1,image2.jpg,2.551722,0.259480,0.871947,0.871947,202.027005,25.453599,0.109989,0.813569,0.644821,...,2.641339,2.583464,7.927913,0.549805,0.259480,0.315387,-0.538252,0.614395,0.989201,0.996550
2,image3.jpg,6.206039,0.618669,0.881609,0.881609,290.479083,38.493259,0.287417,0.465086,1.622099,...,6.453880,3.951214,16.582751,1.352757,0.618669,0.663400,-0.495262,0.809447,0.971216,0.991679
3,image4.jpg,1.885596,0.194235,0.828962,0.828962,82.500028,12.126492,0.090015,0.849845,0.524957,...,1.945784,2.379112,5.820273,0.444227,0.194235,0.272537,-0.521013,0.555576,0.991032,0.997319
4,image5.jpg,4.790395,0.481035,0.890599,0.890599,343.387103,44.837110,0.210380,0.629436,1.159005,...,4.978558,3.366307,14.007415,0.979534,0.481035,0.521808,-0.517051,0.743680,0.979213,0.993550

<h2>Adding prediction vector</h2>

In [9]:
df1['class']=[0 for ele in df1['Autocorrelation']]
df1.head()

,Filename,Autocorrelation,Contrast,Correlation,Correlation.1,Cluster Prominence,Cluster Shade,Dissimilarity,Energy,Entropy,...,Sum average,Sum variance,Sum entropy,Difference variance,Difference entropy,Information measure of correlation1,Informaiton measure of correlation2,Inverse difference normalized,Inverse difference moment normalized,class
0,image1.jpg,4.937605,0.423813,0.894121,0.894121,231.248614,32.252113,0.232233,0.518499,1.458699,...,3.548803,12.964904,1.228323,0.423813,0.586963,-0.528501,0.805223,0.976092,0.994058,0
1,image2.jpg,2.551722,0.259480,0.871947,0.871947,202.027005,25.453599,0.109989,0.813569,0.644821,...,2.583464,7.927913,0.549805,0.259480,0.315387,-0.538252,0.614395,0.989201,0.996550,0
2,image3.jpg,6.206039,0.618669,0.881609,0.881609,290.479083,38.493259,0.287417,0.465086,1.622099,...,3.951214,16.582751,1.352757,0.618669,0.663400,-0.495262,0.809447,0.971216,0.991679,0
3,image4.jpg,1.885596,0.194235,0.828962,0.828962,82.500028,12.126492,0.090015,0.849845,0.524957,...,2.379112,5.820273,0.444227,0.194235,0.272537,-0.521013,0.555576,0.991032,0.997319,0
4,image5.jpg,4.790395,0.481035,0.890599,0.890599,343.387103,44.837110,0.210380,0.629436,1.159005,...,3.366307,14.007415,0.979534,0.481035,0.521808,-0.517051,0.743680,0.979213,0.993550,0

In [10]:
df2['class']=[1 for ele in df2['Autocorrelation']]
df2.head()

,Filename,Autocorrelation,Contrast,Correlation,Correlation.1,Cluster Prominence,Cluster Shade,Dissimilarity,Energy,Entropy,...,Sum average,Sum variance,Sum entropy,Difference variance,Difference entropy,Information measure of correlation1,Informaiton measure of correlation2,Inverse difference normalized,Inverse difference moment normalized,class
0,image1.jpg,4.081557,0.228376,0.929174,0.929174,184.214663,28.044606,0.149079,0.617572,1.122181,...,3.214877,11.239080,0.974364,0.228376,0.438310,-0.608080,0.790244,0.984258,0.996668,1
1,image2.jpg,1.994036,0.136706,0.894339,0.894339,130.419456,16.761857,0.060257,0.871529,0.449294,...,2.379634,6.382350,0.396672,0.136706,0.199795,-0.618673,0.575366,0.994029,0.998174,1
2,image3.jpg,4.123309,0.308980,0.922264,0.922264,483.040290,54.566770,0.136248,0.742517,0.857663,...,3.027194,12.900864,0.733172,0.308980,0.381024,-0.595993,0.718833,0.986485,0.995906,1
3,image4.jpg,4.516132,0.320267,0.921874,0.921874,401.558717,48.037231,0.170913,0.646703,1.137061,...,3.241676,13.031317,0.971226,0.320267,0.470040,-0.565688,0.769051,0.982487,0.995526,1
4,image5.jpg,3.076799,0.218284,0.911018,0.911018,204.893225,27.507612,0.125174,0.738275,0.852772,...,2.799757,8.981627,0.727372,0.218284,0.377198,-0.598837,0.719192,0.987039,0.996884,1

In [11]:
df3['class']=[2 for ele in df3['Autocorrelation']]
df3.head()

,Filename,Autocorrelation,Contrast,Correlation,Correlation.1,Cluster Prominence,Cluster Shade,Dissimilarity,Energy,Entropy,...,Sum average,Sum variance,Sum entropy,Difference variance,Difference entropy,Information measure of correlation1,Informaiton measure of correlation2,Inverse difference normalized,Inverse difference moment normalized,class
0,image1.jpg,8.372510,0.442759,0.925101,0.925101,255.859479,27.115212,0.304044,0.315781,1.987220,...,4.749099,20.812079,1.677746,0.442759,0.703275,-0.560855,0.887026,0.967682,0.993472,2
1,image2.jpg,10.460629,0.275223,0.955780,0.955780,182.128877,5.924040,0.230927,0.278508,1.783799,...,5.472205,27.383920,1.572047,0.275223,0.580233,-0.603112,0.885896,0.974822,0.995840,2
2,image3.jpg,8.456983,0.402405,0.926625,0.926625,194.581342,18.978737,0.295895,0.272738,2.055704,...,4.864675,20.216486,1.758032,0.402405,0.687674,-0.562526,0.893997,0.968255,0.994017,2
3,image4.jpg,9.186615,0.421785,0.925223,0.925223,170.293355,11.796909,0.310501,0.258401,2.040796,...,5.129270,22.424199,1.728484,0.421785,0.706414,-0.545834,0.884900,0.966690,0.993719,2
4,image5.jpg,9.096118,0.436322,0.929328,0.929328,248.651792,23.881550,0.305198,0.276225,2.088801,...,4.991025,22.224721,1.779439,0.436322,0.702735,-0.557034,0.894205,0.967471,0.993559,2

<h2> Removing unwanted columns</h2>

In [12]:
df1=df1.drop(labels='Filename',axis=1)
df2=df2.drop(labels='Filename',axis=1)
df3=df3.drop(labels='Filename',axis=1)
df1.head()

,Autocorrelation,Contrast,Correlation,Correlation.1,Cluster Prominence,Cluster Shade,Dissimilarity,Energy,Entropy,Homogeneity,...,Sum average,Sum variance,Sum entropy,Difference variance,Difference entropy,Information measure of correlation1,Informaiton measure of correlation2,Inverse difference normalized,Inverse difference moment normalized,class
0,4.937605,0.423813,0.894121,0.894121,231.248614,32.252113,0.232233,0.518499,1.458699,0.907496,...,3.548803,12.964904,1.228323,0.423813,0.586963,-0.528501,0.805223,0.976092,0.994058,0
1,2.551722,0.259480,0.871947,0.871947,202.027005,25.453599,0.109989,0.813569,0.644821,0.961702,...,2.583464,7.927913,0.549805,0.259480,0.315387,-0.538252,0.614395,0.989201,0.996550,0
2,6.206039,0.618669,0.881609,0.881609,290.479083,38.493259,0.287417,0.465086,1.622099,0.893214,...,3.951214,16.582751,1.352757,0.618669,0.663400,-0.495262,0.809447,0.971216,0.991679,0
3,1.885596,0.194235,0.828962,0.828962,82.500028,12.126492,0.090015,0.849845,0.524957,0.967822,...,2.379112,5.820273,0.444227,0.194235,0.272537,-0.521013,0.555576,0.991032,0.997319,0
4,4.790395,0.481035,0.890599,0.890599,343.387103,44.837110,0.210380,0.629436,1.159005,0.925256,...,3.366307,14.007415,0.979534,0.481035,0.521808,-0.517051,0.743680,0.979213,0.993550,0

<h2> Concatenate Dataframes</h2>

In [13]:
df_main=pd.concat([df1,df2,df3],axis=0)
df_main.head()

,Autocorrelation,Contrast,Correlation,Correlation.1,Cluster Prominence,Cluster Shade,Dissimilarity,Energy,Entropy,Homogeneity,...,Sum average,Sum variance,Sum entropy,Difference variance,Difference entropy,Information measure of correlation1,Informaiton measure of correlation2,Inverse difference normalized,Inverse difference moment normalized,class
0,4.937605,0.423813,0.894121,0.894121,231.248614,32.252113,0.232233,0.518499,1.458699,0.907496,...,3.548803,12.964904,1.228323,0.423813,0.586963,-0.528501,0.805223,0.976092,0.994058,0
1,2.551722,0.259480,0.871947,0.871947,202.027005,25.453599,0.109989,0.813569,0.644821,0.961702,...,2.583464,7.927913,0.549805,0.259480,0.315387,-0.538252,0.614395,0.989201,0.996550,0
2,6.206039,0.618669,0.881609,0.881609,290.479083,38.493259,0.287417,0.465086,1.622099,0.893214,...,3.951214,16.582751,1.352757,0.618669,0.663400,-0.495262,0.809447,0.971216,0.991679,0
3,1.885596,0.194235,0.828962,0.828962,82.500028,12.126492,0.090015,0.849845,0.524957,0.967822,...,2.379112,5.820273,0.444227,0.194235,0.272537,-0.521013,0.555576,0.991032,0.997319,0
4,4.790395,0.481035,0.890599,0.890599,343.387103,44.837110,0.210380,0.629436,1.159005,0.925256,...,3.366307,14.007415,0.979534,0.481035,0.521808,-0.517051,0.743680,0.979213,0.993550,0

In [14]:
df_main.describe()

,Autocorrelation,Contrast,Correlation,Correlation.1,Cluster Prominence,Cluster Shade,Dissimilarity,Energy,Entropy,Homogeneity,...,Sum average,Sum variance,Sum entropy,Difference variance,Difference entropy,Information measure of correlation1,Informaiton measure of correlation2,Inverse difference normalized,Inverse difference moment normalized,class
count,192.000000,192.000000,192.000000,192.000000,192.000000,192.000000,192.000000,192.000000,192.000000,192.000000,...,192.000000,192.000000,192.000000,192.000000,192.000000,192.000000,192.000000,192.000000,192.000000,192.000000
mean,4.573637,0.268571,0.896885,0.896885,177.143063,19.952697,0.159041,0.632742,1.080797,0.934148,...,3.362680,12.227574,0.927930,0.268571,0.415215,-0.573578,0.704298,0.983417,0.996195,1.020833
std,3.147084,0.135100,0.043796,0.043796,81.769198,9.804233,0.097084,0.257692,0.665400,0.044638,...,1.167284,7.299367,0.568358,0.135100,0.201610,0.054625,0.152985,0.010510,0.001968,0.785726
min,1.192696,0.038599,0.758959,0.758959,19.710267,-7.483682,0.018399,0.191741,0.138469,0.844161,...,2.082085,4.293570,0.123163,0.038599,0.075501,-0.718767,0.331383,0.961323,0.991679,0.000000
25%,2.105185,0.160458,0.865038,0.865038,118.120970,12.942858,0.072317,0.315043,0.493837,0.892566,...,2.426678,6.620598,0.427745,0.160458,0.230502,-0.610384,0.583406,0.974446,0.994640,0.000000
50%,3.055012,0.262109,0.912535,0.912535,170.426233,18.764016,0.137972,0.716502,0.895940,0.948060,...,2.804838,8.886739,0.767411,0.262109,0.392671,-0.567283,0.706412,0.985968,0.996326,1.000000
75%,7.483346,0.370147,0.930238,0.930238,229.559781,25.492773,0.240104,0.858719,1.784732,0.973690,...,4.613299,18.068471,1.552272,0.370147,0.600653,-0.534954,0.880958,0.992765,0.997839,2.000000
max,14.311495,0.618669,0.964613,0.964613,483.040290,54.566770,0.366055,0.966052,2.270148,0.993272,...,6.557724,36.534593,1.927983,0.618669,0.787256,-0.435715,0.906791,0.998155,0.999467,2.000000

In [15]:
df_main.isna().sum()

Autocorrelation                         0
Contrast                                0
Correlation                             0
Correlation.1                           0
Cluster Prominence                      0
Cluster Shade                           0
Dissimilarity                           0
Energy                                  0
Entropy                                 0
 Homogeneity                            0
Homogeneity: [2]                        0
Maximum probability:                    0
Sum of sqaures: Variance                0
Sum average                             0
Sum variance                            0
Sum entropy                             0
Difference variance                     0
Difference entropy                      0
Information measure of correlation1     0
Informaiton measure of correlation2     0
Inverse difference normalized           0
Inverse difference moment normalized    0
class                                   0
dtype: int64

In [16]:
#no null values creating a csv file from this
df_main.to_csv('./Data/test_data.csv',index=False)

In [17]:
data=pd.read_csv('./Data/test_data.csv')
data.head()

,Autocorrelation,Contrast,Correlation,Correlation.1,Cluster Prominence,Cluster Shade,Dissimilarity,Energy,Entropy,Homogeneity,...,Sum average,Sum variance,Sum entropy,Difference variance,Difference entropy,Information measure of correlation1,Informaiton measure of correlation2,Inverse difference normalized,Inverse difference moment normalized,class
0,4.937605,0.423813,0.894121,0.894121,231.248614,32.252113,0.232233,0.518499,1.458699,0.907496,...,3.548803,12.964904,1.228323,0.423813,0.586963,-0.528501,0.805223,0.976092,0.994058,0
1,2.551722,0.259480,0.871947,0.871947,202.027005,25.453599,0.109989,0.813569,0.644821,0.961702,...,2.583464,7.927913,0.549805,0.259480,0.315387,-0.538252,0.614395,0.989201,0.996550,0
2,6.206039,0.618669,0.881609,0.881609,290.479083,38.493259,0.287417,0.465086,1.622099,0.893214,...,3.951214,16.582751,1.352757,0.618669,0.663400,-0.495262,0.809447,0.971216,0.991679,0
3,1.885596,0.194235,0.828962,0.828962,82.500028,12.126492,0.090015,0.849845,0.524957,0.967822,...,2.379112,5.820273,0.444227,0.194235,0.272537,-0.521013,0.555576,0.991032,0.997319,0
4,4.790395,0.481035,0.890599,0.890599,343.387103,44.837110,0.210380,0.629436,1.159005,0.925256,...,3.366307,14.007415,0.979534,0.481035,0.521808,-0.517051,0.743680,0.979213,0.993550,0